dofile("Tools.lua")
dofile("GroundUnits/WeaponSystem/Tools/weapons.lua")
dofile("GroundUnits/WeaponSystem/Tools/CannonSounds.lua")
dofile("GroundUnits/WeaponSystem/Tools/AutoGunSounds.lua")
dofile("GroundUnits/WeaponSystem/Tools/MissileSounds.lua")

Pantsir_SM_weapons = weapons:new()

Pantsir_SM_weapons:addTurret(1, "GndTech/TurretRotation_Electric")

Pantsir_SM_weapons:addLauncher(1, 1, automatic_gun_2A38)
Pantsir_SM_weapons:addLauncher(2, 1, automatic_gun_2A38)
Pantsir_SM_weapons:addLauncher(3, 1, automatic_gun_2A38)
Pantsir_SM_weapons:addLauncher(4, 1, automatic_gun_2A38)
Pantsir_SM_weapons:addLauncher(5, 1, automatic_gun_2A38)
Pantsir_SM_weapons:addLauncher(6, 1, automatic_gun_2A38)
Pantsir_SM_weapons:addLauncher(1, 2, _9M311)
Pantsir_SM_weapons:addLauncher(2, 2, _9M311)
Pantsir_SM_weapons:addLauncher(3, 2, _9M311)
Pantsir_SM_weapons:addLauncher(4, 2, _9M311)
Pantsir_SM_weapons:addLauncher(5, 2, _9M311)
Pantsir_SM_weapons:addLauncher(6, 2, _9M311)

-- Pantsir_SM_weapons:addLauncher(1, 1, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(2, 1, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(3, 1, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(4, 1, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(5, 1, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(6, 1, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(1, 2, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(2, 2, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(3, 2, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(4, 2, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(5, 2, automatic_gun_2A38)
-- Pantsir_SM_weapons:addLauncher(6, 2, automatic_gun_2A38)