livery = {
	{"Material.001",	DIFFUSE			,	"Pantsir_Grating", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Window",	DIFFUSE			,	"fuchstransp", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Window",	DIFFUSE			,	"fuchstransp", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Camo_net",	DIFFUSE			,	"ERO_Camo_Netting_L", true};
	{"Camo:net2",	DIFFUSE			,	"ERO_Camo_Netting_L", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Pantsir",	DIFFUSE			,	"Russian_Sand1B", true};
	{"Pantsir",	SPECULAR			,	"Russian_Green_Rough1", true};
	{"Material.008",	DIFFUSE			,	"FLAME_ZU_03", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Under Carriage",	DIFFUSE			,	"Pantsir_desert2", true};
	{"Material.032",	DIFFUSE			,	"US_Soldier_Driver", true};
	{"Material.002",	DIFFUSE			,	"US_Soldier_Driver", true};
	{"Russian_INF_Camo",	DIFFUSE			,	"Russian_Infantry_Camo", true};
	{"Pantsir_Black",	DIFFUSE			,	"Pantsir_desert2", true};
}
name = "Russian Desert Camo 2"